# Generated by Django 5.1.5 on 2025-01-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, help_text='Xodim ID', max_length=50, null=True, verbose_name='Xodim ID')),
                ('citizenship', models.CharField(blank=True, help_text='Fuqaroligini kirting', max_length=100, null=True, verbose_name='Fuqaroligi')),
                ('passport', models.CharField(blank=True, help_text='Passport seriyasini kiritish lozim', max_length=9, null=True, verbose_name='Passport seriyasi')),
                ('personal_number', models.CharField(blank=True, help_text='Shaxsiy raqamini kiritish lozim', max_length=14, null=True, verbose_name='Shaxsiy raqami (JSHER)')),
                ('faculty', models.CharField(blank=True, help_text='Fakultetini kiritish lozim', max_length=100, null=True, verbose_name='Fakulteti')),
                ('department', models.CharField(blank=True, help_text="Kafedra/Bo'limini kiritish lozim", max_length=100, null=True, verbose_name="Kafedra/Bo'lim")),
                ('frist_name', models.CharField(blank=True, help_text='Ismini kiritish lozim', max_length=50, null=True, verbose_name='Ismi')),
                ('last_name', models.CharField(blank=True, help_text='Familiyasini kiritish lozim', max_length=50, null=True, verbose_name='Familiyasi')),
                ('sur_name', models.CharField(blank=True, help_text='Otasining ismini kiritish lozim', max_length=50, null=True, verbose_name='Otasining ismi')),
                ('labor_form', models.CharField(blank=True, help_text='Ish shaklini kiritish lozim', max_length=100, null=True, verbose_name='Ish shakli')),
                ('stavka', models.CharField(blank=True, help_text='Stavkani kiritish lozim', max_length=100, null=True, verbose_name='Stavka')),
                ('position', models.CharField(blank=True, help_text='Lavozimini kiritish lozim', max_length=100, null=True, verbose_name='Lavozimi')),
                ('academic_degree', models.CharField(blank=True, help_text='Ilmiy darajasini kiriting', max_length=100, null=True, verbose_name='Ilmiy darajasi')),
                ('academic_title', models.CharField(blank=True, help_text='Ilmiy unvonini kiriting', max_length=100, null=True, verbose_name='Ilmiy unvon')),
                ('expertise', models.CharField(blank=True, help_text='Mutaxassisligini kiritish lozim', max_length=200, null=True, verbose_name='Mutaxassisligi')),
                ('start_position', models.CharField(blank=True, help_text='Ishga kirigan sanasini kiritish lozim', max_length=10, null=True, verbose_name='Ishga kirgan sana')),
                ('contract_number', models.CharField(blank=True, help_text='Shartnoma raqamini kiriting', max_length=100, null=True, verbose_name='Shartnoma raqami')),
                ('contract_date', models.CharField(blank=True, help_text='Shartnoma sanasini kiriting', max_length=100, null=True, verbose_name='Shartnoma sanasi')),
                ('order_number', models.CharField(blank=True, help_text='Buyruq raqamini kiriting', max_length=100, null=True, verbose_name='Buyruq raqami')),
                ('order_date', models.CharField(blank=True, help_text='Buyruq sanasini kiriting', max_length=100, null=True, verbose_name='Buyruq sanasi')),
                ('bithday', models.CharField(blank=True, help_text="Tug'ilgan kunini kiritish lozim", max_length=20, null=True, verbose_name="Tug'ilgan kun")),
                ('age', models.IntegerField(blank=True, help_text='Yoshini kiritish lozim', null=True, verbose_name='Yoshi')),
                ('gender', models.CharField(blank=True, help_text='Jinsini kiritish lozim', max_length=10, null=True, verbose_name='Jinsi')),
                ('email', models.EmailField(blank=True, help_text='Email manzilimi kiritish', max_length=100, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Telefon raqamini kiritish lozim', max_length=13, null=True, verbose_name='Telefon raqami')),
                ('permanent_registration', models.CharField(blank=True, help_text='Doimiy yashash joyini kiritish lozim', max_length=250, null=True, verbose_name='Doimiy yashash joyi')),
                ('organization', models.CharField(blank=True, help_text='Tashkilotini kiritish lozim', max_length=200, null=True, verbose_name='Tashkiloti nomi')),
                ('nationality', models.CharField(blank=True, help_text='Millatini kiritish lozim', max_length=50, null=True, verbose_name='Millati')),
                ('place_of_birth', models.CharField(blank=True, help_text="Tug'ilgan joyini kiritish lozim", max_length=200, null=True, verbose_name="Tug'ilgan joyi")),
                ('city', models.CharField(blank=True, help_text='Tuman yoki shaharni kiritish lozim', max_length=200, null=True, verbose_name='Tuman yoki Shaxar')),
                ('graduation_end_year', models.CharField(blank=True, help_text="Oliy ta'lim tugatgan yili", max_length=250, null=True, verbose_name="Oliy ta'lim muassasasini tugatgan yili")),
                ('end_education', models.CharField(blank=True, help_text="Tugatgan oliy ta'limini kiritish lozim", max_length=50, null=True, verbose_name="Tugatgan oliy ta'limi nomi")),
            ],
            options={
                'verbose_name': 'Xodimlar',
                'verbose_name_plural': "Xodimlar ro'yxati",
            },
        ),
    ]
