# Generated by Django 5.1.5 on 2025-01-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Xodim ID', max_length=50, null=True, unique=True, verbose_name='Xodim ID'),
        ),
    ]
