# Generated by Django 5.1.5 on 2025-01-28 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_role_userrole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Rol yaratish', 'verbose_name_plural': 'Rollar'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='contract_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='contract_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='labor_form',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='start_position',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='stavka',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Rol nomi'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.TextField(verbose_name='ruxsatlar'),
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(blank=True, help_text='Fakultetini kiritish lozim', max_length=100, null=True, verbose_name='Fakulteti')),
                ('department', models.CharField(blank=True, help_text="Kafedra/Bo'limini kiritish lozim", max_length=100, null=True, verbose_name="Kafedra/Bo'lim")),
                ('labor_form', models.CharField(blank=True, help_text='Ish shaklini kiritish lozim', max_length=100, null=True, verbose_name='Ish shakli')),
                ('stavka', models.CharField(blank=True, help_text='Stavkani kiritish lozim', max_length=100, null=True, verbose_name='Stavka')),
                ('position', models.CharField(blank=True, help_text='Lavozimini kiritish lozim', max_length=100, null=True, verbose_name='Lavozimi')),
                ('expertise', models.CharField(blank=True, help_text='Mutaxassisligini kiritish lozim', max_length=200, null=True, verbose_name='Mutaxassisligi')),
                ('start_position', models.CharField(blank=True, help_text='Ishga kirigan sanasini kiritish lozim', max_length=10, null=True, verbose_name='Ishga kirgan sana')),
                ('contract_number', models.CharField(blank=True, help_text='Shartnoma raqamini kiriting', max_length=100, null=True, verbose_name='Shartnoma raqami')),
                ('contract_date', models.CharField(blank=True, help_text='Shartnoma sanasini kiriting', max_length=100, null=True, verbose_name='Shartnoma sanasi')),
                ('order_number', models.CharField(blank=True, help_text='Buyruq raqamini kiriting', max_length=100, null=True, verbose_name='Buyruq raqami')),
                ('order_date', models.CharField(blank=True, help_text='Buyruq sanasini kiriting', max_length=100, null=True, verbose_name='Buyruq sanasi')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xodim', to='employee.employee', verbose_name='Xodimlar')),
            ],
            options={
                'verbose_name': "Xodimlar bo'limi",
                'verbose_name_plural': "Xodimlar bo'limi",
            },
        ),
    ]
