# Generated by Django 5.1.5 on 2025-02-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_rename_frist_name_employee_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='end_education_mag',
            field=models.CharField(blank=True, help_text="Tugatgan oliy ta'limini kiritish lozim", max_length=50, null=True, verbose_name="Tugatgan oliy ta'limi nomi (Magistrt)"),
        ),
        migrations.AddField(
            model_name='employee',
            name='graduation_end_year_mag',
            field=models.CharField(blank=True, help_text="Oliy ta'lim tugatgan yili", max_length=250, null=True, verbose_name="Oliy ta'lim muassasasini tugatgan yili (Magistrt)"),
        ),
    ]
