# Generated by Django 5.1.5 on 2025-02-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_end_education_mag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(blank=True, help_text='Xodim ID', max_length=50, null=True, unique=True, verbose_name='Xodim ID'),
        ),
    ]
